#!/usr/bin/env python3
"""
Test script for Usage Tracker - simulates data with mock values
"""

import sys
sys.path.insert(0, '/home/lumadmin/.openclaw/workspace/scripts')

from datetime import datetime

# Mock data for testing
openai_data = {
    'total_spent': 12.45,
    'days_used': 11,
    'daily_average': 1.13,
    'period_start': '2026-03-01',
    'period_end': '2026-03-11'
}

copilot_data = {
    'seats_used': 1,
    'total_seats': 1,
    'total_cost': 10.00
}

def format_report(openai_data, copilot_data):
    """Format the usage report for Discord."""
    report = []
    report.append("📊 **Hourly Usage Report**")
    report.append(f"🕐 *{datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}*")
    report.append("")
    
    # OpenAI Section
    report.append("🔵 **OpenAI Usage**")
    if openai_data:
        report.append(f"• Period: {openai_data['period_start']} to {openai_data['period_end']}")
        report.append(f"• Total Spent: ${openai_data['total_spent']:.2f}")
        report.append(f"• Days Used: {openai_data['days_used']}")
        report.append(f"• Daily Average: ${openai_data['daily_average']:.2f}")
    else:
        report.append("• No data available")
    
    report.append("")
    
    # GitHub Copilot Section
    report.append("🟢 **GitHub Copilot Usage**")
    if copilot_data:
        report.append(f"• Seats: {copilot_data['seats_used']}/{copilot_data['total_seats']}")
        report.append(f"• Monthly Cost: ${copilot_data['total_cost']:.2f}")
    else:
        report.append("• No data available")
    
    report.append("")
    report.append("---")
    report.append("*Report generated by Usage Tracker cron job*")
    
    return "\n".join(report)

# Generate test report
report = format_report(openai_data, copilot_data)
print("Test Report:")
print(report)
print("\n" + "="*50)
print("To enable real tracking:")
print("1. Set OPENAI_API_KEY in your environment")
print("2. Set GITHUB_TOKEN in your environment")
print("3. The cron job will run hourly automatically")
